apiVersion: v1
kind: Service
metadata:
    name: "aksrawad-a445"
    labels:
        app: "aksrawad-a445"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksrawad-a445"