on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: rgcrawad.azurecr.io
        username: ${{ secrets.acr_rgcrawad_username }}
        password: ${{ secrets.acr_rgcrawad_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t rgcrawad.azurecr.io/aksrawad:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push rgcrawad.azurecr.io/aksrawad:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksrawad_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-rawad | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-rawad`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-rawad
        container-registry-url: rgcrawad.azurecr.io
        container-registry-username: ${{ secrets.acr_rgcrawad_username }}
        container-registry-password: ${{ secrets.acr_rgcrawad_password }}
        secret-name: aksrawaddockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-rawad
        manifests: |
          manifests/deployment-10.yml
          manifests/service-10.yml
        images: |
          rgcrawad.azurecr.io/aksrawad:${{ github.sha }}
        imagepullsecrets: |
          aksrawaddockerauth
